### ISSUE TITLE
Tuple doesn't implement Applicative

### ISSUE THREAD

**Issue by gabejohnson** [dustinws/zoom#1]
The first reason is because it doesn't implement `Apply` (no `ap` function). If you _did_ implement it, `A` would be constrained to having `Semigroup`.

The second reason is that `of` is a unary function (Tuple's version takes two arguments). Your version would implement `Biapplicative` _if_ you also had a `biap` but this isn't a FL algebra. You'd also do well to change the name in that case to `biof` (?).

I have yet to find a reasonable way to implement `of` for a tuple/pair. It would constrain `A` to having `Monoid` and you'd have to determine at runtime which `Monoid`'s `empty` to use.

There's a Sanctuary lib that I've been working on that provides similar capabilities https://github.com/sanctuary-js/sanctuary-pair/tree/gabejohnson/everything

**Comment by dustinws** [comment]
Oh shoot, you are absolutely right. This is the result of me confusing the order of `Apply` and `Applicative`, thinking that `Apply` implemented `Applicative` and not the other way around. That's why there is no `.ap` method. Great catch, I was working off of memory and should have paid more attention to the spec.

For the time being, I think the cleanest solution is dropping the `Applicative` contract, and using the `Tuple(0, 0)` constructor instead of the misused `Tuple.of(0, 0)`. I would like to put Tuple in a place where it is honest about what it implements. `Functor` and `Setoid` seem fine to stay.

Do you have any thoughts on that?

**Comment by gabejohnson** [comment]
`Functor` and `Setoid` look fine. You're technically implementing `Bifunctor` as well by having `mapLeft` in addition to `map`
```js
const bimap = (f, g, t) => mapLeft(f, map(g, t));
```
`sanctuary-pair` also implements Ord, Semigroupoid, Semigroup, Apply, Chain, Foldable,Traversable, Extend, and Extract. Though unless you have the need, there's no real reason for `Tuple` to implement them.

**Comment by dustinws** [comment]
Howdy, just wanted to say that this has been fixed, and the docs have been updated. I'll be adding `Bifunctor` very soon!

Thanks for flagging!
